version: "3.9"

services:

  db:
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

  app:
    image: ${DOCKER_HUB_USERNAME}/tasks-api:${IMAGE_TAG}
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M

  nginx:
    image: ${DOCKER_HUB_USERNAME}/tasks-nginx:${IMAGE_TAG}
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
